version: '3.8'

services:
  kronos-bot:
    build: .
    container_name: kronos_automator
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - TZ=Europe/Madrid
    env_file:
      - .env
    volumes:
      - ./bot.log:/app/bot.log
      - ./kronos.db:/app/kronos.db
    shm_size: '2gb' 
